parameters:
#    shead_user.example.class: Shead\UserBundle\Example

services:
#    shead_user.example:
#        class: %shead_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
