parameters:
#    shead_fencing.example.class: Shead\FencingBundle\Example

services:
#    shead_fencing.example:
#        class: %shead_fencing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
