<?php

namespace Shead\FencingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArbcompRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArbcompRepository extends EntityRepository
{
}
