<?php

namespace Shead\FencingBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Shead\FencingBundle\Entity\Clubs;

/**
 * ClubsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubsRepository extends EntityRepository
{
	
}
